### PR TITLE
UrlForMixin now offers a url property (resolves #193)

### LINKED ISSUE #193: url property for models
Any REST API we build will require a `url` property for all the entity types. Coaster can provide it as a mixin. The `url` property will essentially return `self.url_for(_external=True)`.

### PR DESCRIPTION
**Pull request by jace**

### CODE REVIEW

**Comment by jace** [comment]
Several models have a `url` column. The column will override the property, but we'll have to careful about unintended mixups and should consider renaming those columns.

https://github.com/search?q=org%3Ahasgeek+%22url+%3D+db.Column%22&type=Code

**Comment by jace** [comment]
I'm a little concerned about forcing a `url` property to be available on all models just because `UrlForMixin` is a base class of `BaseMixin`. We need this to be more intent-based:

RoleMixin should look for a dictionary named `proxy_properties` or `__proxy_properties__` mapping names to functions. These will be made available in the proxy as properties.

Syntax 1 (read-only properties):

```python
class MyModel(BaseMixin, db.Model):
    proxy_properties = {
        'url': lambda self: self.url_for(),
        }
```

Syntax 2 (read/write, but verbose):
```python
class MyModel(BaseMixin, db.Model):
    proxy_properties = {
        'url': {'get': lambda self: self.url_for()},
        }
```

Neither syntax offers a way to declare what roles these properties are available under. Presumably, that will be left to `__roles__`.

On the other hand, if `url` turns out to be widely used property, this syntax is unnecessary verbiage in all models. We could take yet another approach: a new mixin dedicated to adding URL properties:

```python
class UrlPropertyMixin(object):
    @with_roles(read={'all'})
    @property
    def url(self):
        return self.url_for()
```

Models that need `url` can simply inherit from this class. Other models are not affected.

**Comment by iambibhas** [comment]
I like the `UrlPropertyMixin` idea but can we call it `absolute_url` instead of `url`? And let it be available to *all* models? I'm getting the idea from Django where each model has a `get_absolute_url()` method that's used internally in Django whenever a url is needed for a model. It can be overridden as well. https://docs.djangoproject.com/en/2.1/ref/models/instances/#get-absolute-url

This lets us get out of this `url` name confusion.

**Comment by jace** [comment]
If we call it `absolute_url`, it doesn't need to be in a separate mixin.

**Comment by jace** [comment]
Renamed. Good to merge, @iambibhas?

**Pull request merged**
